apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffeeapiservice
  name: coffeeapiservice
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: coffeeapi
  type: ClusterIP