apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffeeapi
  name: coffeeapi
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: coffeeapi
  type: ClusterIP